language: python
python:
- 3.9
install:
- pip install -r requirements.txt
script:
- black --check .
- flake8 --max-line-length=99 .
- coverage run manage.py test
- coverage xml
- COVERALLS_REPO_TOKEN=U8Iq8dldiAQQsaOGKkHuVn4LQtDegXBgS coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "swe1-app2"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-891377382249"
  on:
    repo: savnair/swe1-app
    branch: main
  skip_cleanup: 'true'
